flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HTTP-4000.3.7
- StateVar-1.1.0.4
- aeson-0.11.3.0
- ansi-terminal-0.7.1.1
- ansi-wl-pprint-0.6.8.1
- api-builder-0.12.0.0
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.1.1
- attoparsec-0.13.2.0
- base-orphans-0.6
- base64-bytestring-1.0.0.1
- basement-0.0.3
- bifunctors-5.4.2
- blaze-builder-0.4.0.2
- byteable-0.1.1
- cabal-doctest-1.0.3
- case-insensitive-1.2.0.10
- cereal-0.5.4.0
- colour-2.3.3
- comonad-5.0.2
- connection-0.2.8
- contravariant-1.4
- cookie-0.4.2.1
- cryptonite-0.24
- data-default-class-0.1.2.0
- distributive-0.5.3
- dlist-0.8.0.3
- exceptions-0.8.3
- fail-4.9.0.0
- foundation-0.0.16
- free-4.12.4
- hashable-1.2.6.1
- hourglass-0.2.10
- http-client-0.5.7.0
- http-client-tls-0.3.5.1
- http-types-0.9.1
- integer-logarithms-1.0.2
- memory-0.14.8
- mime-types-0.1.0.7
- mtl-2.2.1
- network-2.6.3.2
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- optparse-applicative-0.14.0.0
- parsec-3.1.11
- pem-0.2.2
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2.1
- random-1.1
- reddit-0.2.1.0
- scientific-0.3.5.2
- semigroupoids-5.2.1
- semigroups-0.18.3
- socks-0.5.5
- split-0.2.3.2
- stm-2.4.4.1
- streaming-commons-0.1.18
- syb-0.7
- tagged-0.8.5
- text-1.2.2.2
- tls-1.3.11
- transformers-compat-0.5.1.4
- unordered-containers-0.2.8.0
- vector-0.11.0.0
- void-0.7.2
- x509-1.7.2
- x509-store-1.6.5
- x509-system-1.6.6
- x509-validation-1.6.9
- zlib-0.6.1.2
resolver: ghc-8.0.2
